source 'https://rubygems.org'

gem 'rails', '4.0.4'
gem 'sqlite3', '1.3.9'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '3.1.0'
gem 'turbolinks', '2.2.1'
gem 'jbuilder', '~> 1.2'
gem 'annotate', '2.6.2'
gem 'formtastic', github: 'justinfrench/formtastic'
gem 'devise', '3.2.4'
gem 'decent_exposure', '2.3.1'
gem 'therubyracer', '0.12.1'
gem 'haml-rails', '0.5.3'
gem 'bootstrap-sass', '3.1.0.1'
gem 'twitter-bootstrap-rails', '2.2.8'
gem 'formtastic-bootstrap', '2.1.3'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'webrat', '0.7.3'
  gem 'rspec-rails', '2.14.2'
  gem 'factory_girl_rails', '4.4.1'
  gem 'faker', '1.3.0'
  gem 'better_errors', '1.1.0'
  gem 'binding_of_caller', '0.7.2'
end